blank_issues_enabled: true
contact_links:
  - name: D3D Discord
    url: https://discord.gg/4YxQ7s69S
    about: Coordinate contributions and discuss Tristram 3D objects, procedural work and future features. Português também é bem-vindo.
